# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Mon Sep 13 11:31:04 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1024, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.fileviewer = FileViewer(self.splitter)
        self.fileviewer.setObjectName("fileviewer")
        self.verticalLayout = QtGui.QVBoxLayout(self.fileviewer)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.discrete = FileGroupBox(self.fileviewer)
        self.discrete.setFlat(True)
        self.discrete.setCheckable(True)
        self.discrete.setObjectName("discrete")
        self.gridLayout_2 = QtGui.QGridLayout(self.discrete)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget_discrete = ListCategory(self.discrete)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_discrete.sizePolicy().hasHeightForWidth())
        self.listWidget_discrete.setSizePolicy(sizePolicy)
        self.listWidget_discrete.setObjectName("listWidget_discrete")
        self.gridLayout_2.addWidget(self.listWidget_discrete, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.discrete)
        self.boite = FileGroupBox(self.fileviewer)
        self.boite.setFlat(True)
        self.boite.setCheckable(True)
        self.boite.setObjectName("boite")
        self.gridLayout_3 = QtGui.QGridLayout(self.boite)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidget_boite = ListCategory(self.boite)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_boite.sizePolicy().hasHeightForWidth())
        self.listWidget_boite.setSizePolicy(sizePolicy)
        self.listWidget_boite.setObjectName("listWidget_boite")
        self.gridLayout_3.addWidget(self.listWidget_boite, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.boite)
        self.guignols = FileGroupBox(self.fileviewer)
        self.guignols.setFlat(True)
        self.guignols.setCheckable(True)
        self.guignols.setObjectName("guignols")
        self.gridLayout_4 = QtGui.QGridLayout(self.guignols)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_guignols = ListCategory(self.guignols)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_guignols.sizePolicy().hasHeightForWidth())
        self.listWidget_guignols.setSizePolicy(sizePolicy)
        self.listWidget_guignols.setObjectName("listWidget_guignols")
        self.gridLayout_4.addWidget(self.listWidget_guignols, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.guignols)
        self.groland = FileGroupBox(self.fileviewer)
        self.groland.setFlat(True)
        self.groland.setCheckable(True)
        self.groland.setObjectName("groland")
        self.gridLayout_5 = QtGui.QGridLayout(self.groland)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget_groland = ListCategory(self.groland)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_groland.sizePolicy().hasHeightForWidth())
        self.listWidget_groland.setSizePolicy(sizePolicy)
        self.listWidget_groland.setObjectName("listWidget_groland")
        self.gridLayout_5.addWidget(self.listWidget_groland, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groland)
        self.meteo = FileGroupBox(self.fileviewer)
        self.meteo.setFlat(True)
        self.meteo.setCheckable(True)
        self.meteo.setObjectName("meteo")
        self.gridLayout_6 = QtGui.QGridLayout(self.meteo)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listWidget_meteo = ListCategory(self.meteo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_meteo.sizePolicy().hasHeightForWidth())
        self.listWidget_meteo.setSizePolicy(sizePolicy)
        self.listWidget_meteo.setObjectName("listWidget_meteo")
        self.gridLayout_6.addWidget(self.listWidget_meteo, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.meteo)
        self.petit = FileGroupBox(self.fileviewer)
        self.petit.setFlat(True)
        self.petit.setCheckable(True)
        self.petit.setObjectName("petit")
        self.gridLayout_7 = QtGui.QGridLayout(self.petit)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget_petit = ListCategory(self.petit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_petit.sizePolicy().hasHeightForWidth())
        self.listWidget_petit.setSizePolicy(sizePolicy)
        self.listWidget_petit.setObjectName("listWidget_petit")
        self.gridLayout_7.addWidget(self.listWidget_petit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.petit)
        self.petite = FileGroupBox(self.fileviewer)
        self.petite.setFlat(True)
        self.petite.setCheckable(True)
        self.petite.setObjectName("petite")
        self.gridLayout_8 = QtGui.QGridLayout(self.petite)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listWidget_petite = ListCategory(self.petite)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_petite.sizePolicy().hasHeightForWidth())
        self.listWidget_petite.setSizePolicy(sizePolicy)
        self.listWidget_petite.setObjectName("listWidget_petite")
        self.gridLayout_8.addWidget(self.listWidget_petite, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.petite)
        self.pepites = FileGroupBox(self.fileviewer)
        self.pepites.setFlat(True)
        self.pepites.setCheckable(True)
        self.pepites.setObjectName("pepites")
        self.gridLayout_9 = QtGui.QGridLayout(self.pepites)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.listWidget_pepites = ListCategory(self.pepites)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_pepites.sizePolicy().hasHeightForWidth())
        self.listWidget_pepites.setSizePolicy(sizePolicy)
        self.listWidget_pepites.setObjectName("listWidget_pepites")
        self.gridLayout_9.addWidget(self.listWidget_pepites, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.pepites)
        self.salut = FileGroupBox(self.fileviewer)
        self.salut.setFlat(True)
        self.salut.setCheckable(True)
        self.salut.setObjectName("salut")
        self.gridLayout_10 = QtGui.QGridLayout(self.salut)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.listWidget_salut = ListCategory(self.salut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_salut.sizePolicy().hasHeightForWidth())
        self.listWidget_salut.setSizePolicy(sizePolicy)
        self.listWidget_salut.setObjectName("listWidget_salut")
        self.gridLayout_10.addWidget(self.listWidget_salut, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.salut)
        self.sav = FileGroupBox(self.fileviewer)
        self.sav.setFlat(True)
        self.sav.setCheckable(True)
        self.sav.setObjectName("sav")
        self.gridLayout_11 = QtGui.QGridLayout(self.sav)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.listWidget_sav = ListCategory(self.sav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_sav.sizePolicy().hasHeightForWidth())
        self.listWidget_sav.setSizePolicy(sizePolicy)
        self.listWidget_sav.setObjectName("listWidget_sav")
        self.gridLayout_11.addWidget(self.listWidget_sav, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.sav)
        self.zapping = FileGroupBox(self.fileviewer)
        self.zapping.setFlat(True)
        self.zapping.setCheckable(True)
        self.zapping.setObjectName("zapping")
        self.gridLayout_12 = QtGui.QGridLayout(self.zapping)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listWidget_zapping = ListCategory(self.zapping)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_zapping.sizePolicy().hasHeightForWidth())
        self.listWidget_zapping.setSizePolicy(sizePolicy)
        self.listWidget_zapping.setObjectName("listWidget_zapping")
        self.gridLayout_12.addWidget(self.listWidget_zapping, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.zapping)
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listAvailables = ListAvailables(self.verticalLayoutWidget)
        self.listAvailables.setObjectName("listAvailables")
        self.verticalLayout_2.addWidget(self.listAvailables)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonRefresh = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        self.pushButtonDownload = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout.addWidget(self.pushButtonDownload)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 30))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuOutils = QtGui.QMenu(self.menubar)
        self.menuOutils.setObjectName("menuOutils")
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionPr_f_rences = QtGui.QAction(MainWindow)
        self.actionPr_f_rences.setObjectName("actionPr_f_rences")
        self.action_propos = QtGui.QAction(MainWindow)
        self.action_propos.setObjectName("action_propos")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuOutils.addAction(self.actionPr_f_rences)
        self.menuAide.addAction(self.action_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuOutils.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.petit, QtCore.SIGNAL("toggled(bool)"), self.listWidget_petit.setVisible)
        QtCore.QObject.connect(self.discrete, QtCore.SIGNAL("toggled(bool)"), self.listWidget_discrete.setVisible)
        QtCore.QObject.connect(self.boite, QtCore.SIGNAL("toggled(bool)"), self.listWidget_boite.setVisible)
        QtCore.QObject.connect(self.guignols, QtCore.SIGNAL("toggled(bool)"), self.listWidget_guignols.setVisible)
        QtCore.QObject.connect(self.groland, QtCore.SIGNAL("toggled(bool)"), self.listWidget_groland.setVisible)
        QtCore.QObject.connect(self.meteo, QtCore.SIGNAL("toggled(bool)"), self.listWidget_meteo.setVisible)
        QtCore.QObject.connect(self.petite, QtCore.SIGNAL("toggled(bool)"), self.listWidget_petite.setVisible)
        QtCore.QObject.connect(self.salut, QtCore.SIGNAL("toggled(bool)"), self.listWidget_salut.setVisible)
        QtCore.QObject.connect(self.sav, QtCore.SIGNAL("toggled(bool)"), self.listWidget_sav.setVisible)
        QtCore.QObject.connect(self.zapping, QtCore.SIGNAL("toggled(bool)"), self.listWidget_zapping.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CDL", None, QtGui.QApplication.UnicodeUTF8))
        self.fileviewer.setTitle(QtGui.QApplication.translate("MainWindow", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.discrete.setTitle(QtGui.QApplication.translate("MainWindow", "Action discrète", None, QtGui.QApplication.UnicodeUTF8))
        self.boite.setTitle(QtGui.QApplication.translate("MainWindow", "Boite à questions", None, QtGui.QApplication.UnicodeUTF8))
        self.guignols.setTitle(QtGui.QApplication.translate("MainWindow", "Guignols", None, QtGui.QApplication.UnicodeUTF8))
        self.groland.setTitle(QtGui.QApplication.translate("MainWindow", "Groland", None, QtGui.QApplication.UnicodeUTF8))
        self.meteo.setTitle(QtGui.QApplication.translate("MainWindow", "meteo", None, QtGui.QApplication.UnicodeUTF8))
        self.petit.setTitle(QtGui.QApplication.translate("MainWindow", "Petit journal", None, QtGui.QApplication.UnicodeUTF8))
        self.petite.setTitle(QtGui.QApplication.translate("MainWindow", "Petite semaine", None, QtGui.QApplication.UnicodeUTF8))
        self.pepites.setTitle(QtGui.QApplication.translate("MainWindow", "Pépites du net", None, QtGui.QApplication.UnicodeUTF8))
        self.salut.setTitle(QtGui.QApplication.translate("MainWindow", "SLT", None, QtGui.QApplication.UnicodeUTF8))
        self.sav.setTitle(QtGui.QApplication.translate("MainWindow", "SAV", None, QtGui.QApplication.UnicodeUTF8))
        self.zapping.setTitle(QtGui.QApplication.translate("MainWindow", "Zapping", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setText(QtGui.QApplication.translate("MainWindow", "Rafraichir", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDownload.setText(QtGui.QApplication.translate("MainWindow", "Télécharger", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOutils.setTitle(QtGui.QApplication.translate("MainWindow", "Outils", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("MainWindow", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPr_f_rences.setText(QtGui.QApplication.translate("MainWindow", "Préférences", None, QtGui.QApplication.UnicodeUTF8))
        self.action_propos.setText(QtGui.QApplication.translate("MainWindow", "À propos", None, QtGui.QApplication.UnicodeUTF8))

from CDL import ListCategory, FileGroupBox, FileViewer, ListAvailables
