# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Sat Dec 20 20:10:29 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.downloadsList = DownloadsList(self.tab)
        self.downloadsList.setObjectName(_fromUtf8("downloadsList"))
        self.verticalLayout.addWidget(self.downloadsList)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonBlacklist = QtGui.QPushButton(self.tab)
        self.pushButtonBlacklist.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonBlacklist.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/kblackbox.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonBlacklist.setText(_fromUtf8(""))
        self.pushButtonBlacklist.setObjectName(_fromUtf8("pushButtonBlacklist"))
        self.horizontalLayout.addWidget(self.pushButtonBlacklist)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonRefresh = QtGui.QPushButton(self.tab)
        self.pushButtonRefresh.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonRefresh.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/reload_all_tabs.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonRefresh.setText(_fromUtf8(""))
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        self.pushButtonDownload = QtGui.QPushButton(self.tab)
        self.pushButtonDownload.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonDownload.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/download.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonDownload.setText(_fromUtf8(""))
        self.pushButtonDownload.setObjectName(_fromUtf8("pushButtonDownload"))
        self.horizontalLayout.addWidget(self.pushButtonDownload)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(self.tab1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 745, 2676))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.categoriesList = CategoriesList(self.scrollAreaWidgetContents)
        self.categoriesList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.categoriesList.setFrameShadow(QtGui.QFrame.Raised)
        self.categoriesList.setObjectName(_fromUtf8("categoriesList"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.categoriesList)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.grand = CategoryGroupBox(self.categoriesList)
        self.grand.setCheckable(True)
        self.grand.setObjectName(_fromUtf8("grand"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grand)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.list_grand = VideosList(self.grand)
        self.list_grand.setMinimumSize(QtCore.QSize(0, 200))
        self.list_grand.setAlternatingRowColors(True)
        self.list_grand.setGridStyle(QtCore.Qt.NoPen)
        self.list_grand.setObjectName(_fromUtf8("list_grand"))
        self.gridLayout_4.addWidget(self.list_grand, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.grand)
        self.supplement = CategoryGroupBox(self.categoriesList)
        self.supplement.setCheckable(True)
        self.supplement.setObjectName(_fromUtf8("supplement"))
        self.gridLayout_6 = QtGui.QGridLayout(self.supplement)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.list_supplement = VideosList(self.supplement)
        self.list_supplement.setMinimumSize(QtCore.QSize(0, 200))
        self.list_supplement.setAlternatingRowColors(True)
        self.list_supplement.setGridStyle(QtCore.Qt.NoPen)
        self.list_supplement.setObjectName(_fromUtf8("list_supplement"))
        self.gridLayout_6.addWidget(self.list_supplement, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.supplement)
        self.guignols = CategoryGroupBox(self.categoriesList)
        self.guignols.setFlat(True)
        self.guignols.setCheckable(True)
        self.guignols.setObjectName(_fromUtf8("guignols"))
        self.gridLayout_16 = QtGui.QGridLayout(self.guignols)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.list_guignols = VideosList(self.guignols)
        self.list_guignols.setMinimumSize(QtCore.QSize(0, 200))
        self.list_guignols.setAlternatingRowColors(True)
        self.list_guignols.setGridStyle(QtCore.Qt.NoPen)
        self.list_guignols.setObjectName(_fromUtf8("list_guignols"))
        self.gridLayout_16.addWidget(self.list_guignols, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.guignols)
        self.jt = CategoryGroupBox(self.categoriesList)
        self.jt.setCheckable(True)
        self.jt.setObjectName(_fromUtf8("jt"))
        self.gridLayout_7 = QtGui.QGridLayout(self.jt)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.list_jt = VideosList(self.jt)
        self.list_jt.setMinimumSize(QtCore.QSize(0, 200))
        self.list_jt.setAlternatingRowColors(True)
        self.list_jt.setGridStyle(QtCore.Qt.NoPen)
        self.list_jt.setObjectName(_fromUtf8("list_jt"))
        self.gridLayout_7.addWidget(self.list_jt, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.jt)
        self.groland = CategoryGroupBox(self.categoriesList)
        self.groland.setFlat(True)
        self.groland.setCheckable(True)
        self.groland.setObjectName(_fromUtf8("groland"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groland)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.list_groland = VideosList(self.groland)
        self.list_groland.setMinimumSize(QtCore.QSize(0, 200))
        self.list_groland.setGridStyle(QtCore.Qt.NoPen)
        self.list_groland.setObjectName(_fromUtf8("list_groland"))
        self.gridLayout_17.addWidget(self.list_groland, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groland)
        self.explorateurs = CategoryGroupBox(self.categoriesList)
        self.explorateurs.setCheckable(True)
        self.explorateurs.setObjectName(_fromUtf8("explorateurs"))
        self.gridLayout_5 = QtGui.QGridLayout(self.explorateurs)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.list_explorateurs = VideosList(self.explorateurs)
        self.list_explorateurs.setMinimumSize(QtCore.QSize(0, 200))
        self.list_explorateurs.setAlternatingRowColors(True)
        self.list_explorateurs.setGridStyle(QtCore.Qt.NoPen)
        self.list_explorateurs.setObjectName(_fromUtf8("list_explorateurs"))
        self.gridLayout_5.addWidget(self.list_explorateurs, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.explorateurs)
        self.petit = CategoryGroupBox(self.categoriesList)
        self.petit.setFlat(True)
        self.petit.setCheckable(True)
        self.petit.setObjectName(_fromUtf8("petit"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.petit)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.list_petit = VideosList(self.petit)
        self.list_petit.setMinimumSize(QtCore.QSize(0, 200))
        self.list_petit.setAlternatingRowColors(True)
        self.list_petit.setGridStyle(QtCore.Qt.NoPen)
        self.list_petit.setObjectName(_fromUtf8("list_petit"))
        self.verticalLayout_2.addWidget(self.list_petit)
        self.verticalLayout_4.addWidget(self.petit)
        self.links = CategoryGroupBox(self.categoriesList)
        self.links.setFlat(True)
        self.links.setCheckable(True)
        self.links.setObjectName(_fromUtf8("links"))
        self.gridLayout_20 = QtGui.QGridLayout(self.links)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.list_links = VideosList(self.links)
        self.list_links.setMinimumSize(QtCore.QSize(0, 200))
        self.list_links.setAlternatingRowColors(True)
        self.list_links.setGridStyle(QtCore.Qt.NoPen)
        self.list_links.setObjectName(_fromUtf8("list_links"))
        self.gridLayout_20.addWidget(self.list_links, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.links)
        self.pepites = CategoryGroupBox(self.categoriesList)
        self.pepites.setFlat(True)
        self.pepites.setCheckable(True)
        self.pepites.setObjectName(_fromUtf8("pepites"))
        self.gridLayout_21 = QtGui.QGridLayout(self.pepites)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.list_pepites = VideosList(self.pepites)
        self.list_pepites.setMinimumSize(QtCore.QSize(0, 200))
        self.list_pepites.setAlternatingRowColors(True)
        self.list_pepites.setGridStyle(QtCore.Qt.NoPen)
        self.list_pepites.setObjectName(_fromUtf8("list_pepites"))
        self.gridLayout_21.addWidget(self.list_pepites, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.pepites)
        self.salut = CategoryGroupBox(self.categoriesList)
        self.salut.setFlat(True)
        self.salut.setCheckable(True)
        self.salut.setObjectName(_fromUtf8("salut"))
        self.gridLayout_22 = QtGui.QGridLayout(self.salut)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.list_salut = VideosList(self.salut)
        self.list_salut.setMinimumSize(QtCore.QSize(0, 200))
        self.list_salut.setAlternatingRowColors(True)
        self.list_salut.setGridStyle(QtCore.Qt.NoPen)
        self.list_salut.setObjectName(_fromUtf8("list_salut"))
        self.gridLayout_22.addWidget(self.list_salut, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.salut)
        self.zapping = CategoryGroupBox(self.categoriesList)
        self.zapping.setFlat(True)
        self.zapping.setCheckable(True)
        self.zapping.setObjectName(_fromUtf8("zapping"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.zapping)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.list_zapping = VideosList(self.zapping)
        self.list_zapping.setMinimumSize(QtCore.QSize(0, 200))
        self.list_zapping.setAlternatingRowColors(True)
        self.list_zapping.setGridStyle(QtCore.Qt.NoPen)
        self.list_zapping.setObjectName(_fromUtf8("list_zapping"))
        self.verticalLayout_5.addWidget(self.list_zapping)
        self.verticalLayout_4.addWidget(self.zapping)
        self.gridLayout_2.addWidget(self.categoriesList, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonSeen = QtGui.QPushButton(self.tab1)
        self.pushButtonSeen.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonSeen.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/viewmag+.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonSeen.setText(_fromUtf8(""))
        self.pushButtonSeen.setObjectName(_fromUtf8("pushButtonSeen"))
        self.horizontalLayout_2.addWidget(self.pushButtonSeen)
        self.pushButtonNotSeen = QtGui.QPushButton(self.tab1)
        self.pushButtonNotSeen.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonNotSeen.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/viewmag-.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonNotSeen.setText(_fromUtf8(""))
        self.pushButtonNotSeen.setObjectName(_fromUtf8("pushButtonNotSeen"))
        self.horizontalLayout_2.addWidget(self.pushButtonNotSeen)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonRemove = QtGui.QPushButton(self.tab1)
        self.pushButtonRemove.setEnabled(False)
        self.pushButtonRemove.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonRemove.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/button_cancel.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonRemove.setText(_fromUtf8(""))
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.horizontalLayout_2.addWidget(self.pushButtonRemove)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonPlay = QtGui.QPushButton(self.tab1)
        self.pushButtonPlay.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButtonPlay.setAutoFillBackground(False)
        self.pushButtonPlay.setStyleSheet(_fromUtf8("background-image: url(\":/*.png/resources/video.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;"))
        self.pushButtonPlay.setText(_fromUtf8(""))
        self.pushButtonPlay.setObjectName(_fromUtf8("pushButtonPlay"))
        self.horizontalLayout_2.addWidget(self.pushButtonPlay)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menu_dition = QtGui.QMenu(self.menubar)
        self.menu_dition.setObjectName(_fromUtf8("menu_dition"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFichier.addAction(self.actionQuit)
        self.menu_dition.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menu_dition.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.groland, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_groland.setVisible)
        QtCore.QObject.connect(self.guignols, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_guignols.setVisible)
        QtCore.QObject.connect(self.pepites, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_pepites.setVisible)
        QtCore.QObject.connect(self.zapping, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_zapping.setVisible)
        QtCore.QObject.connect(self.petit, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_petit.setVisible)
        QtCore.QObject.connect(self.links, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_links.setVisible)
        QtCore.QObject.connect(self.salut, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_salut.setVisible)
        QtCore.QObject.connect(self.grand, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_grand.setVisible)
        QtCore.QObject.connect(self.explorateurs, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.list_explorateurs.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "c+dl", None))
        self.pushButtonBlacklist.setToolTip(_translate("MainWindow", "Blacklister les vidéos sélectionnées.\n"
"Elles ne réapparaitront plus dans cette liste", None))
        self.pushButtonRefresh.setToolTip(_translate("MainWindow", "Rafraichir la liste des nouvelles vidéos disponibles", None))
        self.pushButtonDownload.setToolTip(_translate("MainWindow", "Télécharger les vidéos sélectionnées", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Télécharger", None))
        self.grand.setTitle(_translate("MainWindow", "Le Grand Journal", None))
        self.supplement.setTitle(_translate("MainWindow", "Le Supplément", None))
        self.guignols.setTitle(_translate("MainWindow", "Guignols", None))
        self.jt.setTitle(_translate("MainWindow", "Le JT", None))
        self.groland.setTitle(_translate("MainWindow", "Groland", None))
        self.explorateurs.setTitle(_translate("MainWindow", "Les nouveaux explorateurs", None))
        self.petit.setTitle(_translate("MainWindow", "Petit journal", None))
        self.links.setTitle(_translate("MainWindow", "L\'œil de Links", None))
        self.pepites.setTitle(_translate("MainWindow", "Pépites du net", None))
        self.salut.setTitle(_translate("MainWindow", "SLT", None))
        self.zapping.setTitle(_translate("MainWindow", "Zapping", None))
        self.pushButtonSeen.setToolTip(_translate("MainWindow", "Marquée comme vue", None))
        self.pushButtonNotSeen.setToolTip(_translate("MainWindow", "Marquée comme non vue", None))
        self.pushButtonRemove.setToolTip(_translate("MainWindow", "Supprimer la vidéo sélectionnée", None))
        self.pushButtonPlay.setToolTip(_translate("MainWindow", "Lire la vidéo sélectionnée", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Mes vidéos", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menu_dition.setTitle(_translate("MainWindow", "Édition", None))
        self.actionQuit.setText(_translate("MainWindow", "Quitter", None))
        self.actionPreferences.setText(_translate("MainWindow", "Préférences", None))

from CDL import DownloadsList, CategoryGroupBox, CategoriesList
from Video import VideosList
import resources_rc
