# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Preferences.ui'
#
# Created: Tue Mar 15 21:59:27 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(420, 433)
        self.formLayout_2 = QtGui.QFormLayout(Preferences)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(Preferences)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditPlayer = QtGui.QLineEdit(Preferences)
        self.lineEditPlayer.setText("")
        self.lineEditPlayer.setObjectName("lineEditPlayer")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditPlayer)
        self.label_2 = QtGui.QLabel(Preferences)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditDirUser = QtGui.QLineEdit(Preferences)
        self.lineEditDirUser.setObjectName("lineEditDirUser")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditDirUser)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.label_4 = QtGui.QLabel(Preferences)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.frame_2 = QtGui.QFrame(Preferences)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.discrete = QtGui.QCheckBox(self.frame_2)
        self.discrete.setEnabled(False)
        self.discrete.setObjectName("discrete")
        self.gridLayout_2.addWidget(self.discrete, 0, 0, 1, 1)
        self.meteo = QtGui.QCheckBox(self.frame_2)
        self.meteo.setEnabled(False)
        self.meteo.setObjectName("meteo")
        self.gridLayout_2.addWidget(self.meteo, 0, 1, 1, 1)
        self.boite = QtGui.QCheckBox(self.frame_2)
        self.boite.setEnabled(False)
        self.boite.setObjectName("boite")
        self.gridLayout_2.addWidget(self.boite, 1, 0, 1, 1)
        self.petit = QtGui.QCheckBox(self.frame_2)
        self.petit.setObjectName("petit")
        self.gridLayout_2.addWidget(self.petit, 1, 1, 1, 1)
        self.boucan = QtGui.QCheckBox(self.frame_2)
        self.boucan.setObjectName("boucan")
        self.gridLayout_2.addWidget(self.boucan, 2, 0, 1, 1)
        self.petite = QtGui.QCheckBox(self.frame_2)
        self.petite.setEnabled(False)
        self.petite.setObjectName("petite")
        self.gridLayout_2.addWidget(self.petite, 2, 1, 1, 1)
        self.pepites = QtGui.QCheckBox(self.frame_2)
        self.pepites.setObjectName("pepites")
        self.gridLayout_2.addWidget(self.pepites, 3, 1, 1, 1)
        self.guignols = QtGui.QCheckBox(self.frame_2)
        self.guignols.setObjectName("guignols")
        self.gridLayout_2.addWidget(self.guignols, 3, 0, 1, 1)
        self.grand = QtGui.QCheckBox(self.frame_2)
        self.grand.setObjectName("grand")
        self.gridLayout_2.addWidget(self.grand, 4, 0, 1, 1)
        self.groland = QtGui.QCheckBox(self.frame_2)
        self.groland.setObjectName("groland")
        self.gridLayout_2.addWidget(self.groland, 5, 0, 1, 1)
        self.matinale = QtGui.QCheckBox(self.frame_2)
        self.matinale.setEnabled(False)
        self.matinale.setObjectName("matinale")
        self.gridLayout_2.addWidget(self.matinale, 6, 0, 1, 1)
        self.salut = QtGui.QCheckBox(self.frame_2)
        self.salut.setEnabled(False)
        self.salut.setObjectName("salut")
        self.gridLayout_2.addWidget(self.salut, 4, 1, 1, 1)
        self.sav = QtGui.QCheckBox(self.frame_2)
        self.sav.setObjectName("sav")
        self.gridLayout_2.addWidget(self.sav, 5, 1, 1, 1)
        self.zapping = QtGui.QCheckBox(self.frame_2)
        self.zapping.setObjectName("zapping")
        self.gridLayout_2.addWidget(self.zapping, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout)

        self.retranslateUi(Preferences)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Préférences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Preferences", "Player : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Preferences", "Emplacement : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Preferences", "Catégories : ", None, QtGui.QApplication.UnicodeUTF8))
        self.discrete.setText(QtGui.QApplication.translate("Preferences", "Action discrète", None, QtGui.QApplication.UnicodeUTF8))
        self.meteo.setText(QtGui.QApplication.translate("Preferences", "Météo", None, QtGui.QApplication.UnicodeUTF8))
        self.boite.setText(QtGui.QApplication.translate("Preferences", "Boite à questions", None, QtGui.QApplication.UnicodeUTF8))
        self.petit.setText(QtGui.QApplication.translate("Preferences", "Petit journal", None, QtGui.QApplication.UnicodeUTF8))
        self.boucan.setText(QtGui.QApplication.translate("Preferences", "Buzz du jour", None, QtGui.QApplication.UnicodeUTF8))
        self.petite.setText(QtGui.QApplication.translate("Preferences", "Petite semaine", None, QtGui.QApplication.UnicodeUTF8))
        self.pepites.setText(QtGui.QApplication.translate("Preferences", "Pépites du net", None, QtGui.QApplication.UnicodeUTF8))
        self.guignols.setText(QtGui.QApplication.translate("Preferences", "Guignols", None, QtGui.QApplication.UnicodeUTF8))
        self.grand.setText(QtGui.QApplication.translate("Preferences", "Grand Journal", None, QtGui.QApplication.UnicodeUTF8))
        self.groland.setText(QtGui.QApplication.translate("Preferences", "Groland", None, QtGui.QApplication.UnicodeUTF8))
        self.matinale.setText(QtGui.QApplication.translate("Preferences", "Matinale", None, QtGui.QApplication.UnicodeUTF8))
        self.salut.setText(QtGui.QApplication.translate("Preferences", "SLT", None, QtGui.QApplication.UnicodeUTF8))
        self.sav.setText(QtGui.QApplication.translate("Preferences", "SAV", None, QtGui.QApplication.UnicodeUTF8))
        self.zapping.setText(QtGui.QApplication.translate("Preferences", "ZAPPING", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Preferences = QtGui.QWidget()
    ui = Ui_Preferences()
    ui.setupUi(Preferences)
    Preferences.show()
    sys.exit(app.exec_())

